[build]
  command = "npm install"
  publish = "public"
  functions = "src/handlers"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/scrape/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/docs"
  to = "/.netlify/functions/swagger"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
