name = "comicsapi"
main = "src/handlers/api.js"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[build]
  command = "npm run build"

[vars]
  NODE_ENV = "production"

[define]
  "__dirname" = "''"
  "__filename" = "''"

[site]
  bucket = "./public"

[env.production]
  name = "comicsapi"
